Remove disc evidence coversheet
ministryofjustice/Claim-for-Crown-Court-Defence pull request #3651
Opened 2020-12-21 08:41 UTC by kmahern

#### What

#### Ticket

[board ticket description](link)

#### Why

#### How

--------

#### TODO (wip)

 - [ ] item 1
 - [X] item 2

2021-01-04 10:22 UTC, naseberry commented
@kmahern, remember to remove the related stylesheets:

- app/webpack/packs/disc-evidence.js
- app/webpack/stylesheets/pdf.scss

2021-01-04 11:11 UTC, kmahern commented
> @kmahern, remember to remove the related assets:
> 
> * app/webpack/packs/disc-evidence.js
> * app/webpack/stylesheets/pdf.scss

👍 Thank you. I have removed these assets.

2021-01-04 11:26 UTC, jsugarman requested changes
Great stuff, you can also remove these lines from dockerfile

https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/docker/Dockerfile#L22

and 

https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/docker/Dockerfile#L39

2021-01-04 11:29 UTC, jsugarman requested changes
and remove this section from docs

https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/docs/development.md#install-wkhtmltopdf

2021-01-04 11:30 UTC, jsugarman commented
and this line

https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/Brewfile#L6

2021-01-04 11:45 UTC, jrmhaig approved these changes
👍 

The merge conflicts are due to the PRs I've just merged but it should be enough just to recreate `.rubocop_todo.yml`.

2021-01-04 14:35 UTC, kmahern commented
> Great stuff, you can also remove these lines from dockerfile
> 
> https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/docker/Dockerfile#L22
> 
> and
> 
> https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/docker/Dockerfile#L39

👍 have removed wkhtmltopdf from dockerfile

2021-01-04 14:36 UTC, kmahern commented
> and remove this section from docs
> 
> https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/docs/development.md#install-wkhtmltopdf

👍 Have removed reference to wkhtmltopdf from docs

2021-01-04 14:36 UTC, kmahern commented
> and this line
> 
> https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/blob/master/Brewfile#L6

👍 Have removed wkhtmltopdf from brewfile

2021-01-05 14:02 UTC, jsugarman commented on .circleci/config.yml
> -  _install-wkhtmltopdf: &install-wkhtmltopdf
👍 greta, forgot about that

2021-01-05 14:08 UTC, jsugarman approved these changes
Looks good 👍

2021-01-05 14:30 UTC, merged