Fetch attachment path from Active Storage
ministryofjustice/Claim-for-Crown-Court-Defence pull request #3816
Opened 2021-03-16 09:35 UTC by jrmhaig

This allows a rollback from Active Storage to Paperclip.

If an attachment is added using Active Storage the path that is used by
Paperclip to fetch it will fail. The solution is to check to see if an
Active Storage record exists with a key not containing a '/' character (which
would indicate a record previously migrated from Paperclip) then the path
used is calculated by `ActiveStorage::Blob.service.path_for` instead of
Paperclip's pattern.

To enable this to work the stats reports, messages and documents models, when
they are switched to Active Storage, will need to keep populating the Paperclip
fields.

#### What

If an attachment has been created using Active Storage and then Paperclip has been turned back on then fetch the path to the asset from the `ActiveStorage::Blob` record.

#### Ticket

[Migrate paperclip to active storage - stats reports](https://dsdmoj.atlassian.net/browse/CBO-1683)

#### Why

In the event of having to roll back the switch to Active Storage we need to be able to access assets that have been created using Active Storage. However, the pattern for files saved by Active Storage does not match Paperclip.

#### How

Provide a method to the definitions of Paperclip attachments to allow for a dynamically created path. This method will check for the existence of an Active Storage record that has not previously been migrated from Paperclip. This can be checked as the key of an asset migrated from Paperclip will include at least one `/` character.

2021-03-16 11:10 UTC, jsugarman requested changes
Looks good but need
- manual testing of rollback
- unit spec of the mixin
- update the cleanup documentation to get rid of it

2021-03-18 09:11 UTC, jsugarman commented on spec/models/message_spec.rb
> +        ActiveStorage::Attachment.connection.execute(<<~SQL)
can you extract these to a shared context as i did for documents

2021-03-18 09:11 UTC, jsugarman commented on spec/models/message_spec.rb
> +        ActiveStorage::Attachment.connection.execute(<<~SQL)
[as above](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/pull/3816/files#r596672810)

2021-03-18 09:12 UTC, jsugarman commented on spec/models/stats/stats_report_spec.rb
> +        ActiveStorage::Attachment.connection.execute(<<~SQL)
[as above](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/pull/3816/files#r596672810)

2021-03-18 09:12 UTC, jsugarman commented on spec/models/stats/stats_report_spec.rb
> +        ActiveStorage::Attachment.connection.execute(<<~SQL)
[as above](https://github.com/ministryofjustice/Claim-for-Crown-Court-Defence/pull/3816/files#r596672810)

2021-03-18 09:20 UTC, jsugarman requested changes
👍 Looks ok

- needs some `shared_contexts` to DRY out the tests further before merge i'd say.
- **not a blocker** but could even abstract AS setup further to parameterise the differences but probably not worth it. Ideally the AS stuff would have factorybot factories to deal with it too/instead - e.g. `spec/factories/documents.rb`
- have black-box tested on staging for documents and message attachments ✅

2021-03-18 09:42 UTC, jrmhaig commented
> Ideally the AS stuff would have factorybot factories to deal with it too/instead - e.g. `spec/factories/documents.rb`

I don't know how Factory Bot would cope with this. The AS data has be to inserted directly into the database because it is not attached to real associations.

2021-03-18 09:57 UTC, jsugarman approved these changes
👍

2021-03-18 10:02 UTC, jsugarman commented
> > Ideally the AS stuff would have factorybot factories to deal with it too/instead - e.g. `spec/factories/documents.rb`
> 
> I don't know how Factory Bot would cope with this. The AS data has be to inserted directly into the database because it is not attached to real associations.

On a very quick/shallow search [i found this](https://blog.eq8.eu/til/factory-bot-trait-for-active-storange-has_attached.html)

2021-03-18 10:17 UTC, jrmhaig commented
> > > Ideally the AS stuff would have factorybot factories to deal with it too/instead - e.g. `spec/factories/documents.rb`
> > 
> > 
> > I don't know how Factory Bot would cope with this. The AS data has be to inserted directly into the database because it is not attached to real associations.
> 
> On a very quick/shallow search [i found this](https://blog.eq8.eu/til/factory-bot-trait-for-active-storange-has_attached.html) but something for another PR i'd say

The problem is that we need to create an Active Storage attachment without a `has_attached`. At this stage the `Document` model doesn't know anything about Active Storage so a simple:

```ruby
document { fixture_file_upload(Rails.root.join(...) }
```

is going to, at best, create something with Paperclip and

```ruby
document.document.attach(...)
```

will just fail.

2021-03-18 11:18 UTC, merged