Jh/s3 storage canaries
ministryofjustice/Claim-for-Crown-Court-Defence pull request #4480
Opened 2021-12-08 15:45 UTC by jrmhaig

#### What

Upload Canary documents to the S3 buckets for each CCCD environments with names that will attract a malicious user.

#### Ticket

[Add canaries to S3 storage](https://dsdmoj.atlassian.net/jira/software/c/projects/CFP/boards/624?modal=detail&selectedIssue=CFP-326)

#### Why

If an unauthorised user gains access to the S3 buckets then they may download and open files. If one of the Canarytokens is opened then we will get alerted to the breach.

#### How

A new Rake task will create Canarytokens and upload them to S3 as;

* `admin-users.docx`; Based on `docs/samples/canary_base.docx`, containing a table of fake users and passwords.
* `tmp/contents.pdf`;  Based on `docs/samples/canary_base.pdf` - a mostly blank file containing 'TBC'.

#### TODO

 - [ ] Add some notes in `docs/*`

2021-12-14 09:19 UTC, jsugarman requested changes
👌 Some test sharing issues and tweaks, plus a `super` issue to check

2021-12-14 09:19 UTC, jsugarman commented on spec/lib/thinkst_canary/token/shared_examples.rb
> +      let(:token_options) { super().merge(canarytoken: existing_canarytoken) }
never seen this. what is it it calling super on? rspec

2021-12-14 09:19 UTC, jsugarman commented on spec/lib/thinkst_canary/token/shared_examples.rb
> +    let(:canarytoken) { 'canarytoken' }
i think `new_canaryotoken` would be clearer here. relative to existing canarytoken (and the term is use a lot in theses test as well)

2021-12-14 09:19 UTC, jsugarman commented on spec/lib/thinkst_canary/token/pdf_acrobat_reader_spec.rb
> +    before { allow(Faraday::UploadIO).to receive(:new).and_return(file_upload) }
do these belong here or in the shared example? They are repeated for the `doc-msword` version implying they could reside in the shared example - only the key `pdf:` is different

2021-12-14 09:19 UTC, jsugarman commented on lib/thinkst_canary/token/file_based.rb
> +        super(**kwargs)
just `super` needed to pass all args implicitly

2021-12-14 09:19 UTC, jsugarman commented on lib/thinkst_canary/token/doc_msword.rb
>          super(**kwargs)
just `super` needed to pass all args implicitly

2021-12-14 09:19 UTC, jsugarman commented on lib/thinkst_canary/token/null_token.rb
> +        super(**kwargs)
just `super` needed to pass all args implicitly

2021-12-14 09:19 UTC, jsugarman commented on lib/thinkst_canary/token/pdf_acrobat_reader.rb
> +        super(**kwargs)
just `super` needed to pass all args implicitly

2021-12-14 09:20 UTC, jsugarman commented on docs/thinkst_canary.md
> +| Dummy files on S3 | _filename_ in the S3 bucket for the '_environment_' environment - canary_base.docx | `tmp/contents.pdf` and `admin-users.docx` are Canarytokens placed on the S3 buckets for each
🤔 should we be giving this info away in the repo

2021-12-14 09:30 UTC, jsugarman commented
Also, just tried out and locally it should probably raise a useful message instead of failing with connection errors

2021-12-14 10:26 UTC, jrmhaig commented on spec/lib/thinkst_canary/token/shared_examples.rb
> +      let(:token_options) { super().merge(canarytoken: existing_canarytoken) }
`super()` is the previous version of `token_options`.

2021-12-15 14:53 UTC, jsugarman approved these changes
👍

2021-12-16 09:34 UTC, merged