[CFP-327] Task to generate Canarytokens for documents and message attachments
ministryofjustice/Claim-for-Crown-Court-Defence pull request #4520
Opened 2021-12-22 15:33 UTC by jrmhaig

#### What

Tasks to generate Canarytokens saved as documents and message attachments.

#### Ticket

[Document and message canaries](https://dsdmoj.atlassian.net/browse/CFP-327)

#### Why

When logged in as an caseworker it is possible to download any evidence document by hitting the endpoint `documents/<document-id>/download`. An attacker who has gained unauthorized access to CCCD by logging in as a caseworker may use this in a script to download arbitrary documents. By having Canarytokens, not connected to any claims, placed at certain intervals (in terms of document id) could enable us to detect when this has been done.

Eg;

```bash
#!/usr/bin/env bash

# Cookies for an authenticated caseworker user session
COOKIES=...

for i in `seq 100 200`
do
  curl https://claim-crown-court-defence.service.gov.uk/documents/$i/download \
    -L -OJ -H "Cookie: $COOKIES"
done
```

#### How

Create Rake tasks to create new Canarytokens and save them as `Document`s and attachments for `Message`s. Schedule these tasks to run regularly to place Canarytokens regularly near the most recent items in these two models.

--------

#### TODO (wip)

 - [ ] Documents Rake task
 - [ ] Messages Rake task
 - [ ] Schedule Documents Rake task
 - [ ] Schedule Messages Rake task

2022-01-14 14:44 UTC, jsugarman commented on scheduled_tasks/document_canary_task.rb
> +  every '120m'
```suggestion
  every '1d'
```
```suggestion
  every '120m'
```

2022-01-14 14:46 UTC, jsugarman commented on scheduled_tasks/document_canary_task.rb
> +  every '120m'
I think we talked about making fewer of these @jrmhaig

2022-01-14 14:46 UTC, jsugarman commented on scheduled_tasks/document_canary_task.rb
> +  every '120m'
i think we talked about making fewer of these

2022-01-14 14:47 UTC, jsugarman requested changes
If we can just make 1 a day this can go in @jrmhaig

2022-01-17 10:50 UTC, jsugarman approved these changes, later dismissed
👍

2022-01-19 14:10 UTC, jrmhaig commented
(Blocker) There is a daily task that deletes unattached evidence documents (see `scheduled_tasks/document_cleaner_task.rb`) and this needs to be modified before this PR can be merged.

2022-05-10 09:56 UTC, mpw5 commented
> (Blocker) There is a daily task that deletes unattached evidence documents (see `scheduled_tasks/document_cleaner_task.rb`) and this needs to be modified before this PR can be merged.

Would one alternative to changing `scheduled_tasks/document_cleaner_task.rb` be to schedule the `DocumentCanaryTask` to run immediately after the `DocumentCleanerTask`? As the cleaner runs at 04:00 daily, the Canarytoken could be generated at 04:01. That way there would always be a Canarytoken in the database.

If we want multiple tokens to exist simultaneously, then `DocumentCanaryTask` could be changed to batch create a few, or could run several times a day?

2026-07-09 13:23 UTC, AnnaC-C commented
Closed due to redundant code

2026-07-09 13:23 UTC, closed without merging